apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: bdp1rj1nm-go
  janus-idp.io/tekton: bdp1rj1nm-go
  backstage.io/kubernetes-id: bdp1rj1nm-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: bdp1rj1nm-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
