apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: bdp1rj1nm-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: bdp1rj1nm-go 
  name: bdp1rj1nm-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: bdp1rj1nm-go 
